### ISSUE TITLE
change &lt; &gt; < and > sign

### ISSUE THREAD

**Issue by hilmanski** [andreasindal/laravel-markdown#13]
Hey , 

when i write a code inside triple backtick (```), it output the less than and greater sign as text.
so how can i change this '&amp;lt;' and '&amp;gt;' in code tag
since it auto turns &-sign to &amp;amp; 

i know i can use htmlspecialchars decode but it will allow a script to run

**Comment by hilmanrdn** [comment]
i guess it's just htmlspecialchars issue , sorry

**Comment by alsterholm** [comment]
Hi,

This appears to be caused by Parsedown (the library we're using to parse markdown to HTML), which replaces `&` characters with `&amp;` in the parsed HTML.

Unfortunately, it seems that I can't do anything about it. I will, however, continue to research the matter and see if I can come up with a solution.

Best regards

**Comment by alsterholm** [comment]
Hi!

Like I mentioned earlier, this is a problem of the underlying Markdown parser used by default, which is [erusev/parsedown](https://github.com/erusev/parsedown).

If'd like, you can switch to a custom driver using the following method:
```php
app('Indal\Markdown\Parser')->setDriver($driver);
```

The `$driver` has to be an object that implements the `Indal\Markdown\Drivers\MarkdownDriver` interface.
